<!DOCTYPE html>
<html>
    <head>
        <meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
        <title>{{_'system.error:404'}}</title>
    </head>
    <body>
        <div id="header"><h1>{{_'system.serverError'}}</h1></div>
        <div id="content">
            <div class="content-container">
                <fieldset>
                    <h2>{{_'system.error:404'}}</h2>
                    <p>
                        {{_'system.resourceMayHaveBeenDeleted'}}
                    </p>
                </fieldset>
            </div>
        </div>
    </body>
</html>
