<style>
    .main_table{border-spacing:3px; font-size:8pt;}
    .main_table th, .main_table td{vertical-align:top;}
    .main_table th{text-align:left;}
    .error_table{width:100%; border-collapse:collapse; border-spacing:0;}
    .error_table td, .border{ border:1px solid #E0E0E0; }
</style>

<table class="main_table">
    <tr style='background: <?php echo $color ?>;'>
        <th colspan='3' style='text-align:center;'><?php echo $message; ?></th>
    </tr>
    <tr>
        <td style='padding:10px 0 0 0;text-align:center;' colspan='3'><b>File:</b> <?php echo $file; ?></td>
    </tr>
    <tr>
        <td style='text-align:center;' colspan='3'><b>Line:</b> <?php echo $line; ?></td>
    </tr>
    <tr>
        <td colspan='3' style='padding:10px 0 0 0;'>
            <table class="error_table">
                <tr>
                    <th width='5%'>Trace</th>
                    <th>File</th>
                    <th width='5%'>Line</th>
                    <th>Class/Function called</th>
                    <th>Arguments</th>
                </tr>
                <?php
                    $back_trace = debug_backtrace();
                    $back_trace = array_slice($back_trace, 4);
                    $back_trace = array_reverse($back_trace);
                    foreach($back_trace as $trace_num => $array)
                    {
                        $args = '';
                        if(isset($array['args'])){
                            foreach($array['args'] as $arg)
                            {
                               $args .= ErrorHandler::textifyValues($arg).', ' ;
                            }
                            $args = substr($args,0,-2);
                        }

                        echo '<tr>'.
                                '<td>'.($trace_num + 1).'</td>'.
                                '<td>'.((isset($array['file'])) ? str_replace(PATH, '', $array['file']) : '').'</td>'.
                                '<td>'.((isset($array['line'])) ? $array['line'] : '').'</td>'.
                                '<td>'.((isset($array['class'])) ? $array['class'].$array['type'] : '').$array['function'].'()</td>'.
                                '<td><code>'.$args."</code></td>".
                            '</tr>';
                    }
                ?>
            </table>
        </td>
    </tr>
    <tr>
        <td colspan='3' style='padding:10px 0 0 0;'></td>
    </tr>
    <tr>
        <th width='33%'>GET</th>
        <th width='33%'>POST</th>
        <th>SESSION</th>
    </tr>
    <tr>
        <td class='border'>
            <pre><?php echo ErrorHandler::textifyValues($_GET); ?></pre>
        </td>
        <td class='border'>
            <pre><?php echo ErrorHandler::textifyValues($_POST); ?></pre>
        </td>
        <td class='border'>
            <pre><?php echo ErrorHandler::textifyValues($_SESSION); ?></pre>
        </td>
    </tr>
</table>
